name: Release
on:
  push:
    branches:
      - '**'

env:
  AWS_REGION: eu-west-1

jobs:
  release:
    name: Release
    if: github.ref == 'refs/heads/main'
    runs-on: [self-hosted, semantic-release]
    needs:
      - test
    env:
      REPO_URL: ${{ github.event.repository.url }}
      DOCKER_REGISTRY: 219665457812.dkr.ecr.eu-west-1.amazonaws.com
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # we need the full history
      - name: Log-in to ECR
        run: |
          aws ecr get-login-password --region "$AWS_REGION" | docker login --username AWS --password-stdin "$DOCKER_REGISTRY"
      - name: Release
        uses: ./.github/actions/semantic-release
